# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      # https://circleci.com/developer/images/image/cimg/node
      #- image: cimg/node:12.22.1
      #- currently we need this for dynamic import in module tests, ONLY.
      - image: ubuntu:22.04

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    resource_class: large

    steps:
      - checkout

      - run: ./install.sh

      - run: ./build-tc.sh

      - run: ./upload-build.sh
      
